apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp020-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dp020-app
  template:
    metadata:
      labels:
        app: dp020-app
    spec:
      containers:
      - name: dp020-container
        image: 325583868777.dkr.ecr.ca-central-1.amazonaws.com/dp020-repository:latest
        ports:
        - containerPort: 80
